os2display/display-client

.editorconfig, .eslintrc.json, .gitignore, .prettierrc, .prettierrc.json, README.md, public/fixtures/data1.json, public/fixtures/data2.json, src/App.js, src/App.test.js, src/app.js, src/app.test.js, src/debug-bar.js, src/debug-bar.scss, src/debug.test.js, src/index.js
* Adds a debug bar for loading data into the app.
* Adds a state 'content' to App containing the loaded data.
* Adds an event listener for receiving content that sets the content state.
=> AR-474: Added setup for loading content from json files

.github/workflows/pr.yml
https://jira.itkdev.dk/browse/AR-643
=> AR-643: change npm to yarn in pr.yml

package.json, public/fixtures/image-text/slide1.json, public/fixtures/image-text/slide4.json, src/region.js, src/templates/image-text/image-text.js, src/templates/image-text/image-text.scss
=> AR-560: little changes to fit image text to info stand

src/logger/logger.js
Add console as logging transport for prod until other options are selected.
=> AR-707: Added console to prod logging

docker-compose.server.yml, infrastructure/etc/confd/templates/config.tmpl
https://jira.itkdev.dk/browse/AR-717
Added new config template to match required.
=> AR-707: Added changes to config

docker-compose.server.yml, infrastructure/etc/confd/templates/config.tmpl
https://jira.itkdev.dk/browse/AR-717
Removed unused entryPoint from config
=> AR-707: Removed unused entryPoint

src/data-sync/pull-strategy.js
* Added loader for themes. This will make the slide.themeData field available if a theme is selected for a slide.
=> AR-752: Added theme loader to pull strategy

README.md, src/screen.js
https://jira.itkdev.dk/browse/AR-538
=> AR-538: grid fix

docker-compose.server.yml, infrastructure/etc/confd/templates/config.tmpl
https://jira.itkdev.dk/browse/AR-762
Adds APP_SCHEDULING_INTERVAL to config template.
=> AR-762: Added config values to infrastructure templates

package.json, src/app.js, src/index.js, yarn.lock
https://jira.itkdev.dk/browse/AR-793
Changed to session based screen login.
Removed debug bar from dom.
=> AR-793: Changed to session based screen login

src/app.js, src/data-sync/pull-strategy.js
https://jira.itkdev.dk/browse/AR-435
Added tenantKey to header
=> AR-435: Use tenantKey for header

src/region.js, src/slide.js, src/useRemoteComponent.js
https://jira.itkdev.dk/browse/AR-820
Adjusted remote component loading to avoid flickering when only one slide should be shown in a region.
=> AR-820: Adjusted remote component loading to avoid flickering

.github/workflows/docker_build_develop.yml, .github/workflows/docker_build_main.yml, .github/workflows/docker_build_tag.yml
https://jira.itkdev.dk/browse/AR-797
Updated docker build with prod images.
=> AR-797: Added docker image builds for main and tags

docker-compose.server.yml, infrastructure/etc/confd/templates/config.tmpl, public/example_config.json
https://jira.itkdev.dk/browse/AR-820
Added authenticationRefreshTokenEndpoint to template
=> AR-820: Added authenticationRefreshTokenEndpoint to template

infrastructure/Dockerfile, infrastructure/etc/confd/templates/config.tmpl, infrastructure/etc/confd/templates/default.conf.tmpl
No ticket
Changed docker build to account for client hosted at `/client`
=> AR-797: Changed build dir to /client

package.json, public/example_config.json, src/config-loader.js, src/screen.js, yarn.lock
https://jira.itkdev.dk/browse/AR-723
* Adds support for dark mode: In native browser support mode, or library based mode. Configurable in config.json.
=> AR-723: Added dark mode support

public/index.html
=> change desc to OS2Display client

.gitignore, infrastructure/Dockerfile, infrastructure/etc/confd/templates/config.tmpl
https://jira.itkdev.dk/browse/AR-797
Make `/public/release.json` file on docker build
=> AR-797: Make release.json on docker build

.gitignore, README.md, public/example_release.json, src/app.js, src/release-loader.js, src/screen.js
https://jira.itkdev.dk/browse/AR-719
Added checkForUpdates interval.
=> AR-719: Added checkForUpdates interval

src/app.js
There was an inexplicable windows error so I am changing from using "key === "i"" to "code === "KeyI"" which works...
=> AR-826: change from key to code

src/app.js
https://jira.itkdev.dk/browse/AR-838
Adds cursor: none when debug is false.
=> AR-838: Added cursor none when debug is false

src/app.spec.js, src/error-boundary.js, src/error-boundary.scss, src/region.js, src/region.scss, src/schedule.spec.js, src/screen.js, src/screen.scss, src/slide.js, src/slide.scss, src/touch-region.js, src/touch-region.scss
https://jira.itkdev.dk/browse/AR-829
Changed class names to lower case.
=> AR-829: Changed to lower case class names

docker-compose.server.yml, docker-compose.yml, infrastructure/Dockerfile, infrastructure/docker-entrypoint.sh, infrastructure/etc/confd/templates/default.conf.tmpl, infrastructure/etc/confd/templates/nginx.conf.tmpl, infrastructure/run.sh
https://jira.itkdev.dk/browse/AR-875
Updated docker setup to match new itkdev base setup
N/A
N/A
=> Docker update

.docker/vhost.conf, docker-compose.yml
https://jira.itkdev.dk/browse/AR-892
* Changed port in vhost and change from npm start to yarn start.
=> AR-492: Changed port in vhost and change from npm start to yarn start

CHANGELOG.md
=> DISPLAY-986: Release 1.2.6

infrastructure/docker-entrypoint.sh
N/A
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
=> ITKDev: Fixed nginx entry script

CHANGELOG.md, src/data-sync/pull-strategy.js, src/region.js
https://jira.itkdev.dk/browse/SUPP0RT-1119
Only slides with a loaded template should be rendered
=> SUPPORT-1119: Only slides with a loaded template should be rendered

.github/workflows/itkdev_docker_build_develop.yml, .github/workflows/itkdev_docker_build_tag.yml, CHANGELOG.md
https://jira.itkdev.dk/browse/DISPLAY-986
Fix docker image name for itk images
=> DISPLAY-986: Fix docker image name for itk images

.github/workflows/itkdev_docker_build_tag.yml, .github/workflows/os2display_docker_build_tag.yml, CHANGELOG.md
https://jira.itkdev.dk/browse/DISPLAY-986
Fix version not set in release.json
=> DISPLAY-986: Fix version not set in release.json

CHANGELOG.md, src/app.js, src/id-from-path.js
Add releaseVersion, releaseTimestamp and screenId searchParams when starting app.
=> Add releaseVersion, releaseTimestamp and screenId  to searchParams

.docker/vhost.conf, CHANGELOG.md, infrastructure/itkdev/etc/confd/templates/default.conf.tmpl, infrastructure/os2display/etc/confd/templates/default.conf.tmpl, src/app.spec.js
Added max-age and expires 1 hour to config.json and release.json
=> Added max-age and expires 1 hour to config.json and release.json

.docker/vhost.conf, CHANGELOG.md, README.md, infrastructure/itkdev/etc/confd/templates/config.tmpl, infrastructure/itkdev/etc/confd/templates/default.conf.tmpl, infrastructure/os2display/Readme.md, infrastructure/os2display/etc/confd/templates/config.tmpl, infrastructure/os2display/etc/confd/templates/default.conf.tmpl, public/example_config.json, src/app.js, src/app.spec.js, src/config-loader.js, src/data-sync/data-sync.js, src/release-loader.js, src/schedule.spec.js, src/service/contentService.js
https://leantime.itkdev.dk/#/tickets/showTicket/1186
* Changed to apply max-age 7d to all files and added cache busting to config.json and release.json.
* Added "loginCheckTimeout", "configFetchInterval", "refreshTokenTimeout", "releaseTimestampIntervalTimeout" to config.json
* Simplified config.json.
=> 1186: Changed to apply max-age 7d to all files and added cache busting

CHANGELOG.md, infrastructure/itkdev/etc/confd/templates/nginx.conf.tmpl, infrastructure/os2display/etc/confd/templates/nginx.conf.tmpl
https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/1185
Ensure real IP is logged when behind proxy.
N/A
N/A
=> 1185: Ensured real ip is logged in nginx

CHANGELOG.md, package.json, src/schedule.js, src/service/scheduleService.js, yarn.lock
https://leantime.itkdev.dk/#/tickets/showTicket/2000
Fixed RRule evaluation to handle local time correctly.
=> Fixed rrule evaluation to handle local time correctly

.github/workflows/pr.yml, CHANGELOG.md, README.md, src/touch-region.jsx, vite.config.js
https://leantime.itkdev.dk/#/tickets/showTicket/2314
Fixed issue with svg loading
=> Fixed issue with svg loading

CHANGELOG.md, docs/error-codes.md, src/service/token-service.js
https://leantime.itkdev.dk/#/tickets/showTicket/2314
Remove token errors after re-login.
=> Removed token errors when logging in again

.docker/vhost.conf, CHANGELOG.md, infrastructure/itkdev/etc/confd/templates/default.conf.tmpl, infrastructure/os2display/etc/confd/templates/default.conf.tmpl, public/online-check/index.html, src/app.scss
https://leantime.itkdev.dk/dashboard/show?tab=ticketdetails#/tickets/showTicket/2773
- Add `no-cache´ directive to nginx setup
- Minor styling fixes
=> 2773: Add no-cache directive

CHANGELOG.md, src/service/token-service.js, src/util/constants.js
https://leantime.itkdev.dk/#/tickets/showTicket/2804
Avoid ER105 in url when no token exists in local storage.
=> Avoid ER105 in url when no token exists in local storage

CHANGELOG.md
https://leantime.itkdev.dk/dashboard/show?tab=ticketdetails#/tickets/showTicket/2773
Release 2.1.1
=> 2773: Release 2.1.1
